- operation: Add
  participant_description:
    name: pinky1
    group: libi
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.12
        - 0.25